export function getMenuData() {
  return [
    {
      Id: 13,
      Name: "جابجایی پرسنل",
      Link: "/personslocation1",
      Status: 1,
      PId: 8,
      Order: "0",
      Icon: null,
    },
    {
      Id: 7,
      Name: "صفحه اصلی",
      Link: "/mainpage",
      Status: 1,
      PId: 0,
      Order: "1",
      Icon: null,
    },
    {
      Id: 18,
      Name: "تغییر کلمه عبور",
      Link: "/password",
      Status: 1,
      PId: 17,
      Order: "1",
      Icon: null,
    },
    {
      Id: 21,
      Name: "پرسنل زیرمجموعه",
      Link: "/personelreport",
      Status: 1,
      PId: 11,
      Order: "1",
      Icon: null,
    },
    {
      Id: 49,
      Name: "گزارش کارانه پرسنل",
      Link: "/karanehsummary",
      Status: 1,
      PId: 8,
      Order: "10",
      Icon: null,
    },
    {
      Id: 8,
      Name: "فوق العاده عملیاتی",
      Link: "",
      Status: 1,
      PId: 0,
      Order: "2",
      Icon: null,
    },
    {
      Id: 10,
      Name: "بودجه",
      Link: "",
      Status: 1,
      PId: 0,
      Order: "4",
      Icon: null,
    },
    {
      Id: 11,
      Name: "گزارشات",
      Link: "",
      Status: 1,
      PId: 0,
      Order: "5",
      Icon: null,
    },
    {
      Id: 17,
      Name: "مدیریت سیستم",
      Link: "/underconstruction",
      Status: 1,
      PId: 0,
      Order: "6",
      Icon: null,
    },
    {
      Id: 28,
      Name: "ثبت اطلاعات طرح پایش و پویش",
      Link: "/payesh",
      Status: 1,
      PId: 8,
      Order: "7",
      Icon: null,
    },
    {
      Id: 47,
      Name: "تایید درخواست بودجه",
      Link: "/budgetrcommit",
      Status: 1,
      PId: 10,
      Order: "7",
      Icon: null,
    },
    {
      Id: 12,
      Name: "خروج",
      Link: "/",
      Status: 1,
      PId: 0,
      Order: "8",
      Icon: null,
    },
  ];
}
